# Generated by Django 4.0.6 on 2022-12-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lineapedido',
            table='lineapedido',
        ),
    ]
