# Generated by Django 4.0.6 on 2022-12-18 23:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppTienda', '0001_initial'),
        ('Pedidos', '0003_alter_lineapedido_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineaPedido',
            new_name='LineaPedidos',
        ),
    ]
