# Generated by Django 4.0.6 on 2022-12-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0004_rename_lineapedido_lineapedidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedidos',
            old_name='pedido',
            new_name='pedido_id',
        ),
        migrations.RenameField(
            model_name='lineapedidos',
            old_name='producto',
            new_name='producto_id',
        ),
    ]
