# Generated by Django 4.0.6 on 2022-12-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0005_rename_pedido_lineapedidos_pedido_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedidos',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedidos',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
