# Generated by Django 4.0.6 on 2022-12-18 23:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppTienda', '0001_initial'),
        ('Pedidos', '0006_rename_pedido_id_lineapedidos_pedido_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineaPedidos',
            new_name='LineaPedido',
        ),
    ]
